services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: shortenurl
      POSTGRES_PASSWORD: shortenurl
      POSTGRES_DB: shortenurl
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shortenurl"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-7000:
    image: redis:latest
    container_name: redis_7000
    command: >
      redis-server --port 7000 --cluster-enabled yes --cluster-config-file nodes-7000.conf 
      --cluster-node-timeout 5000 --appendonly yes --dir /data
    ports:
      - "7000:7000"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-7001:
    image: redis:latest
    container_name: redis_7001
    command: >
      redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes-7001.conf 
      --cluster-node-timeout 5000 --appendonly yes --dir /data
    ports:
      - "7001:7001"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7001", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-7002:
    image: redis:latest
    container_name: redis_7002
    command: >
      redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes-7002.conf 
      --cluster-node-timeout 5000 --appendonly yes --dir /data
    ports:
      - "7002:7002"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7002", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-7100:
    image: redis:latest
    container_name: redis_7100
    command: >
      redis-server --port 7100 --cluster-enabled yes --cluster-config-file nodes-7100.conf 
      --cluster-node-timeout 5000 --appendonly yes --dir /data
    ports:
      - "7100:7100"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7100", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-7101:
    image: redis:latest
    container_name: redis_7101
    command: >
      redis-server --port 7101 --cluster-enabled yes --cluster-config-file nodes-7101.conf 
      --cluster-node-timeout 5000 --appendonly yes --dir /data
    ports:
      - "7101:7101"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7101", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-7102:
    image: redis:latest
    container_name: redis_7102
    command: >
      redis-server --port 7102 --cluster-enabled yes --cluster-config-file nodes-7102.conf 
      --cluster-node-timeout 5000 --appendonly yes --dir /data
    ports:
      - "7102:7102"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7102", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
